SET LANGUAGE Portuguese; 
select 
 FORMAT(GETDATE(), 'd', 'pt-br')		AS 'Padrão de Data Abreviada'
,datename(DAY,GETDATE())						AS 'DIA'
,month(GETDATE())										AS 'MÊS'
,datename(MONTH,GETDATE())					AS 'NOME MÊS'
,FORMAT(GETDATE(), 'MMM')						AS 'MÊS ABREV'
,datename(YEAR,GETDATE())						AS 'ANO'
,FORMAT(GETDATE(), 'D', 'pt-br' )   AS 'Padrão de Data Completa'
,FORMAT(GETDATE(), 'D')							AS 'DATA EXTENSO - MES'
,FORMAT(GETDATE(), 'f')							AS 'Padrão de Data/Hora Completa (Hora Abreviada)'
,FORMAT(GETDATE(), 'F')							AS 'Padrão de Data/Hora Completa (Hora Completa)'
,FORMAT(GETDATE(), 'F')							AS 'Padrão de Data/Hora Completa (Hora Completa)'
,FORMAT(GETDATE(), 'g')							AS 'Padrão geral de data/hora (hora abreviada)'
,FORMAT(GETDATE(), 'G')							AS 'Padrão geral de data/hora (hora completa)'
,FORMAT(GETDATE(), 'm')							AS 'Padrão de mês/dia'
,FORMAT(GETDATE(), 'o')							AS 'Padrão de data/hora de ida e volta'
,FORMAT(GETDATE(), 'r')							AS 'Padrão RFC1123'
,FORMAT(GETDATE(), 's')							AS 'Padrão de Data/Hora Classificável'
,FORMAT(GETDATE(), 't')							AS 'Padrão de hora abreviada'
,FORMAT(GETDATE(), 'T')							AS 'Padrão de hora completa'
,FORMAT(GETDATE(), 'u')							AS 'Padrão Classificável Universal de Data/Hora'
,FORMAT(GETDATE(), 'U')							AS 'Padrão Universal de Data/Hora Completa'
,FORMAT(GETDATE(), 'y')							AS 'Padrão ano mês.'

select * from sys.syslanguages where name = 'Português'